services:
  mysql:
    image: mariadb:11.4
    logging:
      driver: none
    command: ["--max-allowed-packet=512M"]
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - default
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    ports:
      - 2080:80
      - 20443:443
      - 20443:443/udp
      - 27080:7080
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
      - coolify
    labels:
      - traefik.enable=true


      # --- Router HTTP que redireciona para HTTPS ---
      - "traefik.http.routers.atendeloja-http.entrypoints=http"
      - "traefik.http.routers.atendeloja-http.rule=Host(`atendeloja.com.br`) && PathPrefix(`/`)"
      - "traefik.http.routers.atendeloja-http.middlewares=redirect-to-https@docker"

      # Middleware que faz o redirect para https
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https"

      # 1) HTTPS-only router
      - "traefik.http.routers.atendeloja.entrypoints=https"
      - "traefik.http.routers.atendeloja.rule=Host(`atendeloja.com.br`)"
      - "traefik.http.routers.atendeloja.tls=true"
      - "traefik.http.routers.atendeloja.tls.certresolver=letsencrypt"
      - "traefik.http.routers.atendeloja.middlewares=compress@docker"
      - "traefik.http.routers.atendeloja.service=litespeed@docker"

      # 2) Definição do serviço “litespeed” e porta interna
      - "traefik.http.services.litespeed.loadbalancer.server.port=80"

      # 3) Middleware de compressão
      - "traefik.http.middlewares.compress.compress=true"



      # (se quiser compressão HTTP)
      - traefik.http.middlewares.gzip.compress=true
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.2
    ports:
      - 18080:8080
      - 18443:8443
    environment:
        DATABASE_HOST: mysql
    restart: always
    networks:
      - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    # command: redis-server --requirepass 8b405f60665e48f795752e534d93b722
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node      # roda em nó único
      - xpack.security.enabled=false     # desativa autenticação (só p/ dev)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m   # ajusta heap Java
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
volumes:
  esdata:
networks:
  default:
    driver: bridge
  coolify:
    external: true
